=== Slava02007/LabRabPPKurs2/XMLproject/library.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Определение элемента book -->
    <xs:complexType name="bookType">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="author" type="xs:string"/>
            <xs:element name="year" type="xs:integer"/>
            <xs:element name="price" type="xs:decimal"/>
            <xs:element name="category" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:integer" use="required"/>
        <xs:attribute name="totalCount" type="xs:integer" use="required"/>
        <xs:attribute name="availableCount" type="xs:integer" use="required"/>
    </xs:complexType>

    <!-- Определение корневого элемента library -->
    <xs:element name="library">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" type="bookType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Slava02007/LabRabPPKurs2/XMLproject/library.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="library.xsd">
        
    <book availableCount="8" id="1" totalCount="10">
                
        <title>Java Programming</title>
                
        <author>James Gosling</author>
                
        <year>2020</year>
                
        <price>49.99</price>
                
        <category>programming</category>
            
    </book>
        
    <book availableCount="2" id="2" totalCount="5">
                
        <title>Design Patterns</title>
                
        <author>Erich Gamma</author>
                
        <year>1994</year>
                
        <price>39.99</price>
                
        <category>computer-science</category>
            
    </book>
        
    <book availableCount="7" id="3" totalCount="7">
                
        <title>Effective Java</title>
                
        <author>Joshua Bloch</author>
                
        <year>2018</year>
                
        <price>45.50</price>
                
        <category>programming</category>
            
    </book>
        
    <book availableCount="0" id="4" totalCount="4">
                
        <title>Clean Code</title>
                
        <author>Robert Martin</author>
                
        <year>2008</year>
                
        <price>35.00</price>
                
        <category>programming</category>
            
    </book>
        
    <book availableCount="10" id="5" totalCount="12">
                
        <title>Harry Potter and the Sorcerer's Stone</title>
                
        <author>J.K. Rowling</author>
                
        <year>1997</year>
                
        <price>20.00</price>
                
        <category>fiction</category>
            
    </book>
        
    <book availableCount="4" id="6" totalCount="8">
                
        <title>Harry Potter and the Chamber of Secrets</title>
                
        <author>J.K. Rowling</author>
                
        <year>1998</year>
                
        <price>22.00</price>
                
        <category>fiction</category>
            
    </book>
        
    <book availableCount="1" id="7" totalCount="6">
                
        <title>The Shining</title>
                
        <author>Stephen King</author>
                
        <year>1977</year>
                
        <price>18.99</price>
                
        <category>horror</category>
            
    </book>
        
    <book availableCount="3" id="8" totalCount="5">
                
        <title>It</title>
                
        <author>Stephen King</author>
                
        <year>1986</year>
                
        <price>25.50</price>
                
        <category>horror</category>
            
    </book>
        
    <book availableCount="10" id="9" totalCount="10">
                
        <title>Introduction to Algorithms</title>
                
        <author>Thomas Cormen</author>
                
        <year>2009</year>
                
        <price>80.00</price>
                
        <category>education</category>
            
    </book>
        
    <book availableCount="1" id="10" totalCount="3">
                
        <title>Refactoring</title>
                
        <author>Martin Fowler</author>
                
        <year>1999</year>
                
        <price>42.00</price>
                
        <category>programming</category>
            
    </book>
        
    <book availableCount="5" id="11" totalCount="5">
                
        <title>The Hobbit</title>
                
        <author>J.R.R. Tolkien</author>
                
        <year>1937</year>
                
        <price>15.00</price>
                
        <category>fantasy</category>
            
    </book>
        
    <book availableCount="2" id="12" totalCount="9">
                
        <title>The Lord of the Rings</title>
                
        <author>J.R.R. Tolkien</author>
                
        <year>1954</year>
                
        <price>30.00</price>
                
        <category>fantasy</category>
            
    </book>
        
    <book availableCount="4" id="13" totalCount="4">
                
        <title>Head First Java</title>
                
        <author>Kathy Sierra</author>
                
        <year>2005</year>
                
        <price>28.99</price>
                
        <category>education</category>
            
    </book>
        
    <book availableCount="3" id="14" totalCount="6">
                
        <title>Java Concurrency in Practice</title>
                
        <author>Brian Goetz</author>
                
        <year>2006</year>
                
        <price>50.00</price>
                
        <category>programming</category>
            
    </book>
        
    <book availableCount="6" id="15" totalCount="7">
                
        <title>Spring in Action</title>
                
        <author>Craig Walls</author>
                
        <year>2020</year>
                
        <price>44.99</price>
                
        <category>programming</category>
            
    </book>
    
</library>
